### PR TITLE
add-tags-ajax ... works ... can merge now!!!

### PR DESCRIPTION
**Pull request by ryanandrewmcpherson**
Added what I thought to be necessary for adding the tags with AJAX on
the tags page....getting errors related to the add-tag-ajax.js code....
I'm at an impass for now ... need some assistance... thank you!

### CODE REVIEW

**Comment by bryancharleslong** [comment]
When I ran this branch, I got a JS error "Uncaught TypeError: submitTagButton.addEventListenter is not a function
    at add-tag-ajax.js:16"
I think, put the line inside the xhr.onreadystatechage function so it will load the eventlistener when the page loads.

**Comment by ryanandrewmcpherson** [comment]
I will try that thanks!

**Comment by ryanandrewmcpherson** [comment]
tried what you suggested, didn't seem to work for me

**Comment by bryancharleslong** [comment]
addEventListener is spelled wrong in add-tag-ajax.js

**Comment by ryanandrewmcpherson** [comment]
thanks so much Alan for you help finding what was wrong with the JS!!!

**Pull request merged**
